// CEFR word-level mappings for English
// Based on English Vocabulary Profile (EVP) — common spoken words
// Fallback: unknown words get estimated by length + heuristics
window.CEFR_LEVELS = {
  // ── A1: Beginner (most common function + content words) ──
  "the": "A1","a": "A1","an": "A1","be": "A1","am": "A1","is": "A1","are": "A1","was": "A1","were": "A1",
  "been": "A1","being": "A1","have": "A1","has": "A1","had": "A1","having": "A1","do": "A1","does": "A1",
  "did": "A1","doing": "A1","will": "A1","would": "A1","can": "A1","could": "A1","shall": "A1","should": "A1",
  "may": "A1","might": "A1","must": "A1","i": "A1","you": "A1","he": "A1","she": "A1","it": "A1","we": "A1",
  "they": "A1","me": "A1","him": "A1","her": "A1","us": "A1","them": "A1","my": "A1","your": "A1","his": "A1",
  "its": "A1","our": "A1","their": "A1","mine": "A1","yours": "A1","hers": "A1","ours": "A1","theirs": "A1",
  "this": "A1","that": "A1","these": "A1","those": "A1","here": "A1","there": "A1","not": "A1","no": "A1",
  "yes": "A1","and": "A1","or": "A1","but": "A1","so": "A1","because": "A1","if": "A1","when": "A1","where": "A1",
  "what": "A1","who": "A1","which": "A1","how": "A1","why": "A1","to": "A1","of": "A1","in": "A1","at": "A1",
  "on": "A1","for": "A1","with": "A1","from": "A1","by": "A1","about": "A1","as": "A1","like": "A1","than": "A1",
  "then": "A1","also": "A1","too": "A1","very": "A1","just": "A1","now": "A1","only": "A1","all": "A1","some": "A1",
  "any": "A1","every": "A1","each": "A1","one": "A1","two": "A1","three": "A1","four": "A1","five": "A1",
  "six": "A1","seven": "A1","eight": "A1","nine": "A1","ten": "A1","first": "A1","last": "A1","next": "A1",
  "good": "A1","bad": "A1","big": "A1","small": "A1","new": "A1","old": "A1","young": "A1","long": "A1",
  "high": "A1","low": "A1","hot": "A1","cold": "A1","nice": "A1","happy": "A1","sad": "A1","right": "A1",
  "wrong": "A1","easy": "A1","hard": "A1","early": "A1","late": "A1","fast": "A1","slow": "A1",
  "man": "A1","woman": "A1","child": "A1","people": "A1","person": "A1","family": "A1","friend": "A1",
  "time": "A1","day": "A1","night": "A1","week": "A1","month": "A1","year": "A1","morning": "A1",
  "evening": "A1","today": "A1","tomorrow": "A1","yesterday": "A1","thing": "A1","way": "A1","world": "A1",
  "life": "A1","work": "A1","home": "A1","house": "A1","room": "A1","place": "A1","city": "A1","country": "A1",
  "water": "A1","food": "A1","money": "A1","name": "A1","number": "A1","word": "A1","hand": "A1","eye": "A1",
  "car": "A1","door": "A1","book": "A1","table": "A1","chair": "A1","phone": "A1","computer": "A1",
  "go": "A1","come": "A1","get": "A1","make": "A1","take": "A1","give": "A1","put": "A1","see": "A1",
  "look": "A1","hear": "A1","know": "A1","think": "A1","want": "A1","need": "A1","like": "A1","love": "A1",
  "say": "A1","tell": "A1","ask": "A1","help": "A1","use": "A1","find": "A1","try": "A1","start": "A1",
  "stop": "A1","play": "A1","live": "A1","eat": "A1","drink": "A1","sleep": "A1","read": "A1",
  "write": "A1","buy": "A1","pay": "A1","call": "A1","open": "A1","close": "A1","talk": "A1","walk": "A1",
  "run": "A1","sit": "A1","stand": "A1","listen": "A1","watch": "A1","learn": "A1","teach": "A1","show": "A1",
  "bring": "A1","leave": "A1","turn": "A1","move": "A1","change": "A1","wait": "A1","stay": "A1","feel": "A1",
  "let": "A1","keep": "A1","mean": "A1","become": "A1","happen": "A1","remember": "A1","forget": "A1",
  "understand": "A1","believe": "A1","meet": "A1","speak": "A1","send": "A1","hold": "A1","fall": "A1",
  "break": "A1","cut": "A1","grow": "A1","die": "A1","kill": "A1","win": "A1","lose": "A1","choose": "A1",

  // ── A2: Elementary ──
  "able": "A2","accept": "A2","across": "A2","act": "A2","actually": "A2","add": "A2","afraid": "A2",
  "after": "A2","again": "A2","age": "A2","ago": "A2","agree": "A2","air": "A2","allow": "A2","almost": "A2",
  "alone": "A2","already": "A2","always": "A2","among": "A2","angry": "A2","animal": "A2","answer": "A2",
  "appear": "A2","area": "A2","arm": "A2","arrive": "A2","art": "A2","away": "A2","back": "A2","bank": "A2",
  "base": "A2","beautiful": "A2","begin": "A2","behind": "A2","best": "A2","better": "A2","between": "A2",
  "bike": "A2","bit": "A2","black": "A2","blue": "A2","body": "A2","born": "A2","both": "A2","bread": "A2",
  "bright": "A2","brother": "A2","brown": "A2","build": "A2","bus": "A2","business": "A2","busy": "A2",
  "cake": "A2","care": "A2","carry": "A2","cat": "A2","catch": "A2","center": "A2","certain": "A2",
  "chance": "A2","check": "A2","class": "A2","clean": "A2","clear": "A2","climb": "A2","clothes": "A2",
  "cloud": "A2","coffee": "A2","color": "A2","common": "A2","company": "A2","compare": "A2","complete": "A2",
  "continue": "A2","cook": "A2","cool": "A2","corner": "A2","cost": "A2","could": "A2","count": "A2",
  "course": "A2","cover": "A2","create": "A2","cross": "A2","cry": "A2","culture": "A2","cup": "A2",
  "dance": "A2","dark": "A2","daughter": "A2","dead": "A2","deal": "A2","decide": "A2","deep": "A2",
  "describe": "A2","develop": "A2","die": "A2","different": "A2","difficult": "A2","dinner": "A2","direction": "A2",
  "discover": "A2","discuss": "A2","doctor": "A2","dog": "A2","dollar": "A2","down": "A2","draw": "A2",
  "dream": "A2","dress": "A2","drive": "A2","drop": "A2","dry": "A2","during": "A2","each": "A2",
  "earth": "A2","east": "A2","education": "A2","egg": "A2","eight": "A2","else": "A2","empty": "A2",
  "end": "A2","enjoy": "A2","enough": "A2","enter": "A2","environment": "A2","especially": "A2","even": "A2",
  "ever": "A2","example": "A2","exercise": "A2","expect": "A2","explain": "A2","face": "A2","fact": "A2",
  "fail": "A2","fair": "A2","far": "A2","father": "A2","favorite": "A2","few": "A2","field": "A2",
  "fill": "A2","final": "A2","fine": "A2","finger": "A2","finish": "A2","fire": "A2","fish": "A2",
  "flat": "A2","floor": "A2","fly": "A2","follow": "A2","foot": "A2","foreign": "A2","form": "A2",
  "free": "A2","fresh": "A2","front": "A2","full": "A2","fun": "A2","future": "A2","game": "A2",
  "garden": "A2","general": "A2","girl": "A2","glass": "A2","god": "A2","gold": "A2","government": "A2",
  "great": "A2","green": "A2","ground": "A2","group": "A2","guess": "A2","hair": "A2","half": "A2",
  "hang": "A2","happen": "A2","head": "A2","health": "A2","heart": "A2","heavy": "A2","history": "A2",
  "hit": "A2","hope": "A2","horse": "A2","hospital": "A2","hotel": "A2","hour": "A2","however": "A2",
  "human": "A2","hundred": "A2","hungry": "A2","idea": "A2","important": "A2","include": "A2","increase": "A2",
  "indeed": "A2","inside": "A2","instead": "A2","interest": "A2","job": "A2","join": "A2","jump": "A2",
  "key": "A2","kind": "A2","king": "A2","kitchen": "A2","language": "A2","large": "A2","later": "A2",
  "laugh": "A2","law": "A2","lead": "A2","left": "A2","less": "A2","letter": "A2","level": "A2",
  "lie": "A2","light": "A2","line": "A2","list": "A2","little": "A2","local": "A2","lot": "A2",
  "lunch": "A2","machine": "A2","main": "A2","many": "A2","map": "A2","mark": "A2","market": "A2",
  "matter": "A2","maybe": "A2","member": "A2","message": "A2","middle": "A2","million": "A2","mind": "A2",
  "minute": "A2","miss": "A2","model": "A2","modern": "A2","moment": "A2","more": "A2","most": "A2",
  "mother": "A2","mountain": "A2","mouth": "A2","much": "A2","music": "A2","national": "A2","near": "A2",
  "never": "A2","news": "A2","north": "A2","note": "A2","nothing": "A2","notice": "A2","offer": "A2",
  "office": "A2","often": "A2","oil": "A2","once": "A2","order": "A2","other": "A2","outside": "A2",
  "own": "A2","page": "A2","paint": "A2","pair": "A2","paper": "A2","parent": "A2","park": "A2",
  "part": "A2","party": "A2","pass": "A2","past": "A2","perhaps": "A2","period": "A2","pick": "A2",
  "picture": "A2","piece": "A2","plan": "A2","plant": "A2","point": "A2","police": "A2","poor": "A2",
  "possible": "A2","power": "A2","practice": "A2","prepare": "A2","present": "A2","pretty": "A2","price": "A2",
  "probably": "A2","problem": "A2","produce": "A2","product": "A2","program": "A2","public": "A2","pull": "A2",
  "push": "A2","question": "A2","quiet": "A2","quite": "A2","radio": "A2","rain": "A2","raise": "A2",
  "reach": "A2","real": "A2","reason": "A2","receive": "A2","red": "A2","remain": "A2","report": "A2",
  "rest": "A2","result": "A2","return": "A2","rich": "A2","ride": "A2","ring": "A2","rise": "A2",
  "river": "A2","road": "A2","rock": "A2","round": "A2","rule": "A2","safe": "A2","same": "A2",
  "save": "A2","school": "A2","science": "A2","sea": "A2","season": "A2","second": "A2","seem": "A2",
  "self": "A2","sell": "A2","sense": "A2","serve": "A2","set": "A2","several": "A2","shake": "A2",
  "shape": "A2","share": "A2","short": "A2","side": "A2","sign": "A2","simple": "A2","since": "A2",
  "sing": "A2","sister": "A2","size": "A2","skill": "A2","skin": "A2","sky": "A2","smile": "A2",
  "snow": "A2","social": "A2","society": "A2","son": "A2","song": "A2","soon": "A2","sort": "A2",
  "sound": "A2","south": "A2","space": "A2","special": "A2","spend": "A2","sport": "A2","spring": "A2",
  "star": "A2","state": "A2","step": "A2","still": "A2","story": "A2","street": "A2","strong": "A2",
  "student": "A2","study": "A2","such": "A2","summer": "A2","sun": "A2","sure": "A2","surprise": "A2",
  "sweet": "A2","swim": "A2","system": "A2","team": "A2","thank": "A2","though": "A2","thousand": "A2",
  "through": "A2","throw": "A2","together": "A2","top": "A2","total": "A2","town": "A2","train": "A2",
  "travel": "A2","tree": "A2","true": "A2","type": "A2","until": "A2","usually": "A2","village": "A2",
  "visit": "A2","voice": "A2","wall": "A2","war": "A2","warm": "A2","wash": "A2","weather": "A2","west": "A2",
  "white": "A2","whole": "A2","wide": "A2","wife": "A2","win": "A2","wind": "A2","window": "A2",
  "winter": "A2","wish": "A2","within": "A2","without": "A2","wonder": "A2","wood": "A2","worry": "A2",
  "worse": "A2","worst": "A2","worth": "A2","yard": "A2","yeah": "A2","yet": "A2",

  // ── B1: Intermediate ──
  "ability": "B1","abroad": "B1","absolutely": "B1","achieve": "B1","action": "B1","active": "B1",
  "activity": "B1","actual": "B1","advantage": "B1","advertise": "B1","advice": "B1","affect": "B1",
  "afford": "B1","against": "B1","ahead": "B1","aim": "B1","although": "B1","amount": "B1","ancient": "B1",
  "announce": "B1","apart": "B1","apply": "B1","approach": "B1","argue": "B1","arrange": "B1","assist": "B1",
  "assume": "B1","attack": "B1","attend": "B1","attitude": "B1","attract": "B1","audience": "B1","author": "B1",
  "available": "B1","average": "B1","avoid": "B1","award": "B1","balance": "B1","ball": "B1","band": "B1",
  "bar": "B1","basic": "B1","battle": "B1","bear": "B1","beat": "B1","beauty": "B1","belong": "B1",
  "benefit": "B1","bill": "B1","block": "B1","board": "B1","border": "B1","bottom": "B1","brain": "B1",
  "bridge": "B1","broad": "B1","burn": "B1","camp": "B1","campaign": "B1","capable": "B1","capital": "B1",
  "career": "B1","cause": "B1","celebrate": "B1","cell": "B1","century": "B1","chain": "B1","challenge": "B1",
  "character": "B1","charge": "B1","chief": "B1","choice": "B1","church": "B1","circle": "B1","citizen": "B1",
  "claim": "B1","climate": "B1","club": "B1","coach": "B1","coast": "B1","collection": "B1","combine": "B1",
  "comfort": "B1","command": "B1","comment": "B1","commit": "B1","communicate": "B1","community": "B1",
  "competition": "B1","concern": "B1","condition": "B1","connect": "B1","consider": "B1","contain": "B1",
  "context": "B1","control": "B1","convince": "B1","copy": "B1","correct": "B1","couple": "B1","court": "B1",
  "crack": "B1","crime": "B1","crowd": "B1","current": "B1","damage": "B1","danger": "B1","data": "B1",
  "debate": "B1","decade": "B1","defense": "B1","define": "B1","degree": "B1","deliver": "B1","demand": "B1",
  "department": "B1","depend": "B1","design": "B1","despite": "B1","detail": "B1","determine": "B1",
  "device": "B1","difference": "B1","direct": "B1","disease": "B1","display": "B1","distance": "B1",
  "divide": "B1","document": "B1","double": "B1","doubt": "B1","duty": "B1","edge": "B1","edition": "B1",
  "effect": "B1","effort": "B1","election": "B1","element": "B1","employ": "B1","enable": "B1","energy": "B1",
  "engage": "B1","engine": "B1","enormous": "B1","ensure": "B1","entire": "B1","equal": "B1","error": "B1",
  "escape": "B1","essential": "B1","establish": "B1","event": "B1","eventually": "B1","evidence": "B1",
  "exact": "B1","examine": "B1","exist": "B1","expand": "B1","experience": "B1","experiment": "B1",
  "expert": "B1","express": "B1","extend": "B1","extreme": "B1","factor": "B1","failure": "B1","faith": "B1",
  "familiar": "B1","famous": "B1","fashion": "B1","feature": "B1","figure": "B1","file": "B1","film": "B1",
  "finance": "B1","firm": "B1","fit": "B1","fix": "B1","flow": "B1","focus": "B1","force": "B1","former": "B1",
  "fortune": "B1","forward": "B1","found": "B1","frame": "B1","freedom": "B1","frequently": "B1",
  "function": "B1","fund": "B1","further": "B1","gain": "B1","gap": "B1","gather": "B1","generation": "B1",
  "global": "B1","goal": "B1","grant": "B1","guard": "B1","guide": "B1","handle": "B1","hardly": "B1",
  "height": "B1","highly": "B1","hire": "B1","host": "B1","household": "B1","huge": "B1","identify": "B1",
  "ignore": "B1","illustrate": "B1","image": "B1","imagine": "B1","impact": "B1","improve": "B1",
  "indicate": "B1","individual": "B1","industry": "B1","influence": "B1","inform": "B1","injury": "B1",
  "instance": "B1","intend": "B1","involve": "B1","island": "B1","issue": "B1","item": "B1","judge": "B1",
  "justice": "B1","justify": "B1","knowledge": "B1","lack": "B1","land": "B1","launch": "B1","leader": "B1",
  "league": "B1","legal": "B1","likely": "B1","limit": "B1","link": "B1","literature": "B1","loan": "B1",
  "locate": "B1","loss": "B1","lower": "B1","manage": "B1","manner": "B1","manufacture": "B1","mass": "B1",
  "material": "B1","measure": "B1","media": "B1","memory": "B1","mental": "B1","mention": "B1","merely": "B1",
  "method": "B1","military": "B1","minor": "B1","mission": "B1","mix": "B1","moral": "B1","mostly": "B1",
  "motor": "B1","movement": "B1","murder": "B1","narrow": "B1","nation": "B1","native": "B1","natural": "B1",
  "nearly": "B1","necessary": "B1","neither": "B1","network": "B1","normal": "B1","nuclear": "B1",
  "numerous": "B1","object": "B1","obtain": "B1","obvious": "B1","occur": "B1","official": "B1","operate": "B1",
  "opinion": "B1","opportunity": "B1","option": "B1","organization": "B1","original": "B1","otherwise": "B1",
  "outcome": "B1","overall": "B1","owner": "B1","pace": "B1","pack": "B1","pain": "B1","particularly": "B1",
  "partner": "B1","pattern": "B1","pause": "B1","peace": "B1","perfect": "B1","perform": "B1","personal": "B1",
  "persuade": "B1","phase": "B1","physical": "B1","pile": "B1","plate": "B1","platform": "B1","plus": "B1",
  "policy": "B1","politics": "B1","popular": "B1","population": "B1","position": "B1","positive": "B1",
  "possess": "B1","potential": "B1","prefer": "B1","president": "B1","press": "B1","prevent": "B1",
  "previous": "B1","primary": "B1","principle": "B1","prior": "B1","private": "B1","procedure": "B1",
  "process": "B1","professional": "B1","profit": "B1","progress": "B1","project": "B1","promise": "B1",
  "promote": "B1","proper": "B1","property": "B1","propose": "B1","protect": "B1","prove": "B1","provide": "B1",
  "publish": "B1","purpose": "B1","quality": "B1","quarter": "B1","race": "B1","range": "B1","rapid": "B1",
  "rate": "B1","rather": "B1","realize": "B1","recent": "B1","recognize": "B1","recommend": "B1","record": "B1",
  "reduce": "B1","refer": "B1","reflect": "B1","refuse": "B1","region": "B1","relate": "B1","relationship": "B1",
  "release": "B1","relevant": "B1","religion": "B1","rely": "B1","remove": "B1","replace": "B1","represent": "B1",
  "request": "B1","require": "B1","research": "B1","resource": "B1","respond": "B1","responsibility": "B1",
  "reveal": "B1","review": "B1","risk": "B1","role": "B1","root": "B1","scale": "B1","scene": "B1",
  "schedule": "B1","score": "B1","screen": "B1","search": "B1","section": "B1","secure": "B1","seek": "B1",
  "select": "B1","senior": "B1","separate": "B1","sequence": "B1","series": "B1","serious": "B1","service": "B1",
  "settle": "B1","sexual": "B1","shift": "B1","shock": "B1","shoot": "B1","signal": "B1","significantly": "B1",
  "similar": "B1","site": "B1","situation": "B1","slightly": "B1","smart": "B1","solution": "B1","somebody": "B1",
  "somewhat": "B1","source": "B1","specific": "B1","speech": "B1","split": "B1","spot": "B1","spread": "B1",
  "square": "B1","stable": "B1","staff": "B1","stage": "B1","standard": "B1","statement": "B1","stock": "B1",
  "store": "B1","strategy": "B1","strength": "B1","stress": "B1","strike": "B1","structure": "B1","struggle": "B1",
  "stuff": "B1","subject": "B1","succeed": "B1","success": "B1","suffer": "B1","suggest": "B1","supply": "B1",
  "support": "B1","suppose": "B1","surface": "B1","surround": "B1","survive": "B1","suspect": "B1","sustain": "B1",
  "symbol": "B1","target": "B1","task": "B1","technique": "B1","technology": "B1","tend": "B1","term": "B1",
  "theme": "B1","theory": "B1","therefore": "B1","thick": "B1","thin": "B1","threat": "B1","title": "B1",
  "tone": "B1","tool": "B1","topic": "B1","tough": "B1","track": "B1","trade": "B1","tradition": "B1",
  "transfer": "B1","treat": "B1","trend": "B1","trial": "B1","trip": "B1","troop": "B1","trouble": "B1",
  "trust": "B1","typically": "B1","unique": "B1","unit": "B1","university": "B1","unless": "B1","unlike": "B1",
  "upper": "B1","upset": "B1","user": "B1","value": "B1","variety": "B1","various": "B1","vehicle": "B1",
  "version": "B1","victim": "B1","view": "B1","violence": "B1","vision": "B1","volume": "B1","vote": "B1",
  "waste": "B1","wave": "B1","wealth": "B1","weapon": "B1","weight": "B1","whatever": "B1","whenever": "B1",
  "wherever": "B1","willing": "B1","wise": "B1",

  // ── B2: Upper Intermediate ──
  "abandon": "B2","absence": "B2","abstract": "B2","academic": "B2","access": "B2","accompany": "B2",
  "accomplish": "B2","account": "B2","accurate": "B2","acknowledge": "B2","acquire": "B2","adapt": "B2",
  "adequate": "B2","adjust": "B2","administration": "B2","advance": "B2","affair": "B2","agenda": "B2",
  "aggression": "B2","aid": "B2","alter": "B2","alternative": "B2","amaze": "B2","ambition": "B2",
  "analysis": "B2","angle": "B2","annual": "B2","anticipate": "B2","anxiety": "B2","apparent": "B2",
  "appreciation": "B2","appropriate": "B2","approve": "B2","arise": "B2","aspect": "B2","assemble": "B2",
  "assert": "B2","assess": "B2","asset": "B2","assign": "B2","associate": "B2","assure": "B2","atmosphere": "B2",
  "attach": "B2","attempt": "B2","attribute": "B2","authority": "B2","aware": "B2","barrier": "B2",
  "behalf": "B2","beneath": "B2","besides": "B2","bias": "B2","bond": "B2","boom": "B2","bound": "B2",
  "branch": "B2","brand": "B2","brief": "B2","broadcast": "B2","budget": "B2","burden": "B2","calculate": "B2",
  "capability": "B2","capture": "B2","category": "B2","cease": "B2","channel": "B2","chapter": "B2","chart": "B2",
  "chemical": "B2","circumstance": "B2","cite": "B2","civil": "B2","clarify": "B2","classic": "B2","client": "B2",
  "code": "B2","collapse": "B2","colleague": "B2","commerce": "B2","commission": "B2","commitment": "B2",
  "commodity": "B2","compensation": "B2","complaint": "B2","complex": "B2","component": "B2","concentrate": "B2",
  "concept": "B2","conclude": "B2","concrete": "B2","conduct": "B2","confident": "B2","confirm": "B2",
  "conflict": "B2","confront": "B2","congress": "B2","conscious": "B2","consequence": "B2","conservative": "B2",
  "considerable": "B2","consistent": "B2","constant": "B2","constitute": "B2","construct": "B2","consume": "B2",
  "contact": "B2","contemporary": "B2","contribute": "B2","controversy": "B2","convention": "B2","convert": "B2",
  "cooperate": "B2","core": "B2","corporate": "B2","correspond": "B2","council": "B2","counter": "B2",
  "craft": "B2","criminal": "B2","crisis": "B2","criterion": "B2","critical": "B2","curious": "B2","currency": "B2",
  "cycle": "B2","debate": "B2","debt": "B2","declare": "B2","decline": "B2","defend": "B2","deficit": "B2",
  "definitely": "B2","democracy": "B2","demonstrate": "B2","deny": "B2","depict": "B2","deposit": "B2",
  "depress": "B2","derive": "B2","deserve": "B2","desire": "B2","desperate": "B2","destination": "B2",
  "detect": "B2","dimension": "B2","discipline": "B2","discourse": "B2","dismiss": "B2","dispute": "B2",
  "dissolve": "B2","distinct": "B2","distinguish": "B2","distribute": "B2","diverse": "B2","domain": "B2",
  "domestic": "B2","dominate": "B2","draft": "B2","drama": "B2","dramatic": "B2","dynamic": "B2",
  "economy": "B2","efficient": "B2","eliminate": "B2","embrace": "B2","emerge": "B2","emission": "B2",
  "emotion": "B2","emphasis": "B2","empire": "B2","encounter": "B2","enhance": "B2","enterprise": "B2",
  "enthusiasm": "B2","episode": "B2","equipment": "B2","equivalent": "B2","essentially": "B2","estate": "B2",
  "estimate": "B2","evaluate": "B2","evolution": "B2","evolve": "B2","exceed": "B2","exception": "B2",
  "exclude": "B2","exclusive": "B2","exhibit": "B2","expansion": "B2","exploit": "B2","exploration": "B2",
  "export": "B2","expose": "B2","extension": "B2","external": "B2","extraordinary": "B2","facilitate": "B2",
  "faculty": "B2","fate": "B2","favor": "B2","feedback": "B2","fiction": "B2","fleet": "B2","flexibility": "B2",
  "forecast": "B2","formation": "B2","formula": "B2","foundation": "B2","fraction": "B2","framework": "B2",
  "frequency": "B2","fuel": "B2","fulfill": "B2","fundamental": "B2","gender": "B2","gene": "B2",
  "genuine": "B2","gesture": "B2","govern": "B2","grain": "B2","guarantee": "B2","guideline": "B2",
  "habitat": "B2","headquarters": "B2","highlight": "B2","historian": "B2","horizon": "B2","household": "B2",
  "hypothesis": "B2","ideal": "B2","implement": "B2","implication": "B2","impose": "B2","incentive": "B2",
  "incident": "B2","incorporate": "B2","index": "B2","infrastructure": "B2","initiative": "B2","innovation": "B2",
  "input": "B2","inquiry": "B2","insight": "B2","inspection": "B2","institution": "B2","instrument": "B2",
  "integrate": "B2","intellectual": "B2","intelligence": "B2","intense": "B2","interaction": "B2",
  "interpret": "B2","intervention": "B2","invest": "B2","investigation": "B2","invisible": "B2","irony": "B2",
  "isolate": "B2","joint": "B2","journal": "B2","justification": "B2","label": "B2","landscape": "B2",
  "latter": "B2","layer": "B2","lecture": "B2","legacy": "B2","legislation": "B2","liberal": "B2",
  "likewise": "B2","logic": "B2","maintain": "B2","margin": "B2","maximum": "B2","mechanism": "B2",
  "minimum": "B2","ministry": "B2","minority": "B2","moderate": "B2","modify": "B2","monitor": "B2",
  "mood": "B2","moreover": "B2","motion": "B2","motivate": "B2","mystery": "B2","narrative": "B2",
  "negotiate": "B2","nerve": "B2","nevertheless": "B2","niche": "B2","norm": "B2","notion": "B2",
  "objective": "B2","obligation": "B2","observation": "B2","occupy": "B2","opponent": "B2","opposition": "B2",
  "organ": "B2","orientation": "B2","output": "B2","overcome": "B2","overlook": "B2","overseas": "B2",
  "panel": "B2","paradox": "B2","parameter": "B2","participate": "B2","passage": "B2","passion": "B2",
  "peak": "B2","peer": "B2","penalty": "B2","perceive": "B2","permanent": "B2","permit": "B2","persist": "B2",
  "personality": "B2","perspective": "B2","phenomenon": "B2","philosophy": "B2","plot": "B2","portray": "B2",
  "pose": "B2","precisely": "B2","predict": "B2","premise": "B2","preserve": "B2","primarily": "B2",
  "priority": "B2","proceed": "B2","profound": "B2","prohibit": "B2","prominent": "B2","proportion": "B2",
  "prospect": "B2","protest": "B2","province": "B2","provoke": "B2","psychological": "B2","purchase": "B2",
  "pursue": "B2","radical": "B2","random": "B2","rank": "B2","ratio": "B2","rational": "B2","react": "B2",
  "rebel": "B2","recover": "B2","regime": "B2","register": "B2","regulate": "B2","reinforce": "B2","reject": "B2",
  "relative": "B2","reliable": "B2","relief": "B2","reluctant": "B2","remarkable": "B2","reputation": "B2",
  "resemble": "B2","reserve": "B2","resident": "B2","resign": "B2","resist": "B2","resolution": "B2",
  "resolve": "B2","restore": "B2","restrict": "B2","retain": "B2","retire": "B2","revenue": "B2",
  "reverse": "B2","revolution": "B2","rigid": "B2","ritual": "B2","rural": "B2","sacrifice": "B2",
  "sample": "B2","sanction": "B2","scope": "B2","sector": "B2","segment": "B2","sensitive": "B2",
  "sentiment": "B2","shadow": "B2","shaped": "B2","shelter": "B2","significant": "B2","simulate": "B2",
  "slight": "B2","sole": "B2","somehow": "B2","sophisticated": "B2","span": "B2","specialist": "B2",
  "sphere": "B2","sponsor": "B2","statistics": "B2","status": "B2","stimulate": "B2","straightforward": "B2",
  "strategic": "B2","stretch": "B2","strip": "B2","substantial": "B2","substitute": "B2","sufficient": "B2",
  "summit": "B2","superior": "B2","surgery": "B2","surplus": "B2","surveillance": "B2","survey": "B2",
  "suspend": "B2","symbolic": "B2","tackle": "B2","tale": "B2","temporary": "B2","tension": "B2",
  "territory": "B2","testify": "B2","texture": "B2","thereby": "B2","threshold": "B2","tissue": "B2",
  "tolerance": "B2","trail": "B2","transformation": "B2","transition": "B2","transmit": "B2","transparent": "B2",
  "trigger": "B2","ultimately": "B2","undergo": "B2","undermine": "B2","undertake": "B2","unemployment": "B2",
  "unfold": "B2","unity": "B2","universe": "B2","upgrade": "B2","urban": "B2","utilize": "B2","valid": "B2",
  "variable": "B2","vast": "B2","venture": "B2","verbal": "B2","verify": "B2","versus": "B2","vessel": "B2",
  "via": "B2","violate": "B2","virtual": "B2","virtue": "B2","visible": "B2","vital": "B2","vocabulary": "B2",
  "voluntary": "B2","vulnerable": "B2","welfare": "B2","whereas": "B2","widespread": "B2","witness": "B2",
  "workforce": "B2","workshop": "B2","yield": "B2",

  // ── C1: Advanced ──
  "abolish": "C1","absorption": "C1","abstraction": "C1","academy": "C1","accountability": "C1",
  "accumulation": "C1","acknowledgement": "C1","acquisition": "C1","activation": "C1","acute": "C1",
  "adjacent": "C1","advocate": "C1","aesthetic": "C1","aggregate": "C1","albeit": "C1","alien": "C1",
  "allegation": "C1","alliance": "C1","allocation": "C1","altogether": "C1","ambiguity": "C1","amend": "C1",
  "analogy": "C1","anchor": "C1","anonymous": "C1","apparatus": "C1","arbitrary": "C1","archive": "C1",
  "articulate": "C1","assertion": "C1","autonomous": "C1","benchmark": "C1","biodiversity": "C1",
  "bureaucracy": "C1","calibrate": "C1","catalyst": "C1","chronic": "C1","coalition": "C1","cognitive": "C1",
  "coherent": "C1","coincide": "C1","collapse": "C1","collective": "C1","commence": "C1","complement": "C1",
  "compliance": "C1","compound": "C1","comprise": "C1","conceive": "C1","concurrent": "C1","configuration": "C1",
  "consensus": "C1","consolidate": "C1","constraint": "C1","contend": "C1","continuity": "C1","contradict": "C1",
  "converge": "C1","correlate": "C1","corruption": "C1","credibility": "C1","cumulative": "C1","curriculum": "C1",
  "decay": "C1","decisive": "C1","decree": "C1","dedicated": "C1","defect": "C1","deficiency": "C1",
  "demographic": "C1","denial": "C1","density": "C1","deploy": "C1","depreciation": "C1","designate": "C1",
  "deteriorate": "C1","deviation": "C1","diagnose": "C1","differentiate": "C1","diffusion": "C1","dilemma": "C1",
  "diminish": "C1","diplomatic": "C1","discard": "C1","disclose": "C1","discourse": "C1","discretion": "C1",
  "discrimination": "C1","disrupt": "C1","disseminate": "C1","dissertation": "C1","distort": "C1",
  "distribution": "C1","divert": "C1","doctrine": "C1","elaborate": "C1","embed": "C1","embody": "C1",
  "empirical": "C1","encompass": "C1","endeavor": "C1","endorse": "C1","entail": "C1","entity": "C1",
  "envisage": "C1","epidemic": "C1","equilibrium": "C1","erode": "C1","ethical": "C1","exacerbate": "C1",
  "explicit": "C1","exploitation": "C1","exponential": "C1","facet": "C1","fluctuation": "C1","formulate": "C1",
  "foster": "C1","friction": "C1","frontier": "C1","governance": "C1","gradient": "C1","hierarchy": "C1",
  "homogeneous": "C1","ideology": "C1","illuminate": "C1","immerse": "C1","immunity": "C1","impair": "C1",
  "implicit": "C1","incline": "C1","indigenous": "C1","indispensable": "C1","induce": "C1","inequality": "C1",
  "inevitable": "C1","inhibit": "C1","initiate": "C1","innate": "C1","instability": "C1","integral": "C1",
  "interim": "C1","interface": "C1","intermediate": "C1","intervene": "C1","intricate": "C1",
  "intrinsic": "C1","intuition": "C1","invoke": "C1","jurisdiction": "C1","juxtapose": "C1",
  "legitimate": "C1","lever": "C1","liaison": "C1","manipulate": "C1","marginal": "C1","mature": "C1",
  "mediate": "C1","migrate": "C1","milestone": "C1","mobilize": "C1","monopoly": "C1","municipal": "C1",
  "nuance": "C1","obsolete": "C1","offset": "C1","ongoing": "C1","optimum": "C1","paradigm": "C1",
  "peripheral": "C1","persistent": "C1","pervasive": "C1","pioneer": "C1","plausible": "C1","portfolio": "C1",
  "precede": "C1","predominantly": "C1","preliminary": "C1","prescribe": "C1","prevail": "C1","problematic": "C1",
  "proficiency": "C1","progressive": "C1","projection": "C1","propagate": "C1","protocol": "C1","proxy": "C1",
  "qualitative": "C1","quantitative": "C1","quarterly": "C1","quota": "C1","rationale": "C1","refine": "C1",
  "regression": "C1","reliance": "C1","render": "C1","residual": "C1","resilient": "C1","robust": "C1",
  "saturation": "C1","sceptical": "C1","seminar": "C1","simulate": "C1","societal": "C1","solidarity": "C1",
  "specification": "C1","speculate": "C1","stakeholder": "C1","statutory": "C1","stereotype": "C1",
  "strategic": "C1","streamline": "C1","subjective": "C1","subordinate": "C1","supplement": "C1",
  "sustainability": "C1","synthesis": "C1","systematic": "C1","taxonomy": "C1","terminology": "C1",
  "theoretical": "C1","trajectory": "C1","transcend": "C1","ubiquitous": "C1","undermine": "C1",
  "unprecedented": "C1","validity": "C1","variability": "C1","vendor": "C1","volatile": "C1",
  "whereby": "C1","wholesale": "C1",

  // ── C2: Proficient ──
  "aberration": "C2","abrogate": "C2","acumen": "C2","adamant": "C2","adjudicate": "C2","aegis": "C2",
  "alacrity": "C2","ameliorate": "C2","anathema": "C2","antithesis": "C2","apocryphal": "C2","arbiter": "C2",
  "arcane": "C2","archetype": "C2","asperity": "C2","assiduous": "C2","auspicious": "C2","axiomatic": "C2",
  "bellicose": "C2","bifurcate": "C2","captious": "C2","caveat": "C2","circumspect": "C2","cogent": "C2",
  "commensurate": "C2","conflagration": "C2","conundrum": "C2","debacle": "C2","deleterious": "C2",
  "demagogue": "C2","diatribe": "C2","dichotomy": "C2","disenfranchise": "C2","draconian": "C2",
  "eclectic": "C2","efficacious": "C2","egalitarian": "C2","enervate": "C2","ennui": "C2","ephemeral": "C2",
  "equanimity": "C2","equivocate": "C2","erudite": "C2","eschew": "C2","esoteric": "C2","exacerbate": "C2",
  "excoriate": "C2","exegesis": "C2","exigent": "C2","extrapolate": "C2","facetious": "C2","fastidious": "C2",
  "garrulous": "C2","germane": "C2","gestalt": "C2","hackneyed": "C2","halcyon": "C2","hegemony": "C2",
  "hermeneutic": "C2","hubris": "C2","iconoclast": "C2","idiosyncratic": "C2","ignominious": "C2",
  "immutable": "C2","impasse": "C2","impecunious": "C2","implacable": "C2","inchoate": "C2","incipient": "C2",
  "incongruous": "C2","indefatigable": "C2","ineluctable": "C2","inexorable": "C2","inscrutable": "C2",
  "insouciant": "C2","intransigent": "C2","inveterate": "C2","irrevocable": "C2","jejune": "C2",
  "juxtaposition": "C2","laconic": "C2","laissez": "C2","litigious": "C2","lugubrious": "C2","magnanimous": "C2",
  "malfeasance": "C2","mendacious": "C2","mercurial": "C2","milieu": "C2","misanthrope": "C2","modicum": "C2",
  "moratorium": "C2","munificent": "C2","nefarious": "C2","neologism": "C2","nihilism": "C2","nonchalant": "C2",
  "obfuscate": "C2","obstreperous": "C2","officious": "C2","omnipotent": "C2","onerous": "C2",
  "opprobrium": "C2","panacea": "C2","paradigm": "C2","paroxysm": "C2","peccadillo": "C2","pedantic": "C2",
  "penchant": "C2","perfidious": "C2","perfunctory": "C2","perspicacious": "C2","philistine": "C2",
  "phlegmatic": "C2","plethora": "C2","pragmatic": "C2","precarious": "C2","precipitous": "C2",
  "prerogative": "C2","prodigious": "C2","profligate": "C2","propensity": "C2","propitious": "C2",
  "pugnacious": "C2","punctilious": "C2","quagmire": "C2","quintessential": "C2","quixotic": "C2",
  "recalcitrant": "C2","recidivism": "C2","recondite": "C2","redoubtable": "C2","refractory": "C2",
  "reprehensible": "C2","reprobate": "C2","resplendent": "C2","reticent": "C2","sagacious": "C2",
  "sanguine": "C2","sardonic": "C2","schism": "C2","sedulous": "C2","sinecure": "C2","solicitous": "C2",
  "specious": "C2","spurious": "C2","stolid": "C2","stringent": "C2","surreptitious": "C2",
  "sycophant": "C2","taciturn": "C2","tantamount": "C2","temerity": "C2","tenuous": "C2","torpid": "C2",
  "tractable": "C2","transient": "C2","trenchant": "C2","ubiquitous": "C2","unctuous": "C2",
  "unequivocal": "C2","vacillate": "C2","venerable": "C2","veracity": "C2","verbose": "C2","vicarious": "C2",
  "vicissitude": "C2","vilify": "C2","vindicate": "C2","virtuoso": "C2","vitriolic": "C2","vituperate": "C2",
  "vociferous": "C2","voluptuous": "C2","xenophobia": "C2","zeitgeist": "C2"
};

// Get CEFR level for a word — lookup first, then heuristic fallback
window.getCEFRLevel = function(word) {
  var w = word.toLowerCase().replace(/[^a-z']/g, '');
  if (!w || w.length < 2) return null;
  
  // Direct lookup
  if (window.CEFR_LEVELS[w]) return window.CEFR_LEVELS[w];
  
  // Heuristic fallback
  var len = w.length;
  if (len <= 3) return 'A1';
  if (len <= 5) return 'A2';
  if (len <= 7) return 'B1';
  if (len <= 9) return 'B2';
  if (len <= 11) return 'C1';
  return 'C2';
};

// Color map for CEFR levels — clearly distinguishable
window.CEFR_COLORS = {
  'A1': { bg: '#e2e8f0', text: '#475569', label: 'A1 · Principiante' },
  'A2': { bg: '#bbf7d0', text: '#15803d', label: 'A2 · Elementare' },
  'B1': { bg: '#fef08a', text: '#854d0e', label: 'B1 · Intermedio' },
  'B2': { bg: '#bfdbfe', text: '#1d4ed8', label: 'B2 · Intermedio sup.' },
  'C1': { bg: '#e9d5ff', text: '#6b21a8', label: 'C1 · Avanzato' },
  'C2': { bg: '#fbcfe8', text: '#9d174d', label: 'C2 · Padronanza' }
};
