// js/panoramica/panels/help.js — pnl-aiuto panel
var container = null;

export async function render(parentEl) {
  container = parentEl;
  container.innerHTML = `<div class="content-panel" id="pnl-aiuto">
  <section class="panel-head" style="border-bottom:2px solid var(--line-strong);padding-bottom:24px;margin-bottom:40px"><h2>Aiuto</h2><p style="font-size:15px;color:var(--text-soft);margin:6px 0 0;max-width:600px;line-height:1.5" data-i18n="help_desc">Domande frequenti sul sistema di report, crediti, e sull'affidabilità delle analisi.</p></section>
  <style>#pnl-aiuto .faq-item::before{display:none!important}
    @media(min-width:1024px){ #pnl-aiuto .hlp-grid{grid-template-columns:1fr 2fr} }
  </style>

  <!-- Section: Sistema & Affidabilità -->
  <section style="padding:0 0 48px;border-bottom:2px solid var(--line);margin-bottom:48px">
    <div class="hlp-grid" style="display:grid;gap:32px">
      <div>
        <h3 style="font-size:24px;font-weight:700;color:var(--text);margin:0 0 8px;letter-spacing:-.02em">Sistema &amp; Affidabilità</h3>
        <p style="font-size:13px;color:var(--text-soft);line-height:1.5;margin:0">Come funzionano i report, quanto sono affidabili e come vengono protetti i tuoi dati.</p>
      </div>
      <div style="background:var(--card);border:2px solid var(--line);border-radius:16px;overflow:hidden">
        <div class="faq-item" aria-expanded="false" style="display:flex;align-items:center;justify-content:space-between;padding:22px 28px;cursor:pointer;transition:background .2s;border-bottom:1px solid var(--line)" onmouseover="this.style.background='var(--bg)'" onmouseout="this.style.background=''"><div class="faq-inner" onclick="toggleFAQ(this.parentElement)" style="cursor:pointer;flex:1"><div style="font-size:15px;font-weight:700;color:var(--text);margin-bottom:4px" data-i18n="help_what_are_reports">Cosa sono gli AI Reports?</div><div style="font-size:12px;color:var(--text-soft);line-height:1.5"><span data-i18n="help_reports_preview">Analisi automatiche basate sulle tue sessioni di caption e traduzione.</span></div><div class="faq-a-wrap"><div class="faq-a" style="font-size:14px;color:var(--text-soft);line-height:1.7;padding-top:14px">Gli AI Reports sono analisi generate automaticamente basate sulle tue sessioni di caption e traduzione. Ogni report esamina aspetti diversi: grammatica, vocabolario, fluidità, interferenze dalla lingua madre, e altro ancora. I report usano solo i dati delle tue sessioni reali — non inventano nulla.</div></div></div><span class="material-symbols-outlined" style="color:var(--text-soft);opacity:.4;flex-shrink:0;transition:all .3s;margin-left:16px">chevron_right</span></div>
        <div class="faq-item" aria-expanded="false" style="display:flex;align-items:center;justify-content:space-between;padding:22px 28px;cursor:pointer;transition:background .2s;border-bottom:1px solid var(--line)" onmouseover="this.style.background='var(--bg)'" onmouseout="this.style.background=''"><div class="faq-inner" onclick="toggleFAQ(this.parentElement)" style="cursor:pointer;flex:1"><div style="font-size:15px;font-weight:700;color:var(--text);margin-bottom:4px" data-i18n="help_how_reliable">Quanto sono affidabili?</div><div style="font-size:12px;color:var(--text-soft);line-height:1.5"><span data-i18n="help_reliable_preview">Precisione e modello statistico dei risultati.</span></div><div class="faq-a-wrap"><div class="faq-a" style="font-size:14px;color:var(--text-soft);line-height:1.7;padding-top:14px">L'affidabilità dipende dal numero di sessioni analizzate. Più sessioni = più dati = analisi più solide. Ogni report include una nota sull'affidabilità. I report non assegnano certificazioni ufficiali CEFR e usano un linguaggio prudente.</div></div></div><span class="material-symbols-outlined" style="color:var(--text-soft);opacity:.4;flex-shrink:0;transition:all .3s;margin-left:16px">chevron_right</span></div>
        <div class="faq-item" aria-expanded="false" style="display:flex;align-items:center;justify-content:space-between;padding:22px 28px;cursor:pointer;transition:background .2s;border-bottom:1px solid var(--line)" onmouseover="this.style.background='var(--bg)'" onmouseout="this.style.background=''"><div class="faq-inner" onclick="toggleFAQ(this.parentElement)" style="cursor:pointer;flex:1"><div style="font-size:15px;font-weight:700;color:var(--text);margin-bottom:4px" data-i18n="help_data_safe">I miei dati sono al sicuro?</div><div style="font-size:12px;color:var(--text-soft);line-height:1.5"><span data-i18n="help_safe_preview">Informazioni su privacy e crittografia dei dati.</span></div><div class="faq-a-wrap"><div class="faq-a" style="font-size:14px;color:var(--text-soft);line-height:1.7;padding-top:14px">Sì. Le tue sessioni e i tuoi report sono visibili solo a te. I dati vengono usati esclusivamente per generare i tuoi report personali e non vengono condivisi con terze parti.</div></div></div><span class="material-symbols-outlined" style="color:var(--text-soft);opacity:.4;flex-shrink:0;transition:all .3s;margin-left:16px">chevron_right</span></div>
        <div class="faq-item" aria-expanded="false" style="display:flex;align-items:center;justify-content:space-between;padding:22px 28px;cursor:pointer;transition:background .2s" onmouseover="this.style.background='var(--bg)'" onmouseout="this.style.background=''"><div class="faq-inner" onclick="toggleFAQ(this.parentElement)" style="cursor:pointer;flex:1"><div style="font-size:15px;font-weight:700;color:var(--text);margin-bottom:4px" data-i18n="help_replace_teacher">Il report sostituisce un insegnante?</div><div style="font-size:12px;color:var(--text-soft);line-height:1.5"><span data-i18n="help_teacher_preview">Come integrare il feedback AI con i metodi tradizionali.</span></div><div class="faq-a-wrap"><div class="faq-a" style="font-size:14px;color:var(--text-soft);line-height:1.7;padding-top:14px">No. È uno strumento di analisi e orientamento: trasforma dati reali in feedback utile. Non valuta la tua pronuncia, non interagisce con te, e non sostituisce il giudizio di un professionista.</div></div></div><span class="material-symbols-outlined" style="color:var(--text-soft);opacity:.4;flex-shrink:0;transition:all .3s;margin-left:16px">chevron_right</span></div>
      </div>
    </div>
  </section>

  <!-- Section: Crediti & Accesso -->
  <section style="padding:0 0 48px">
    <div class="hlp-grid" style="display:grid;gap:32px">
      <div>
        <h3 style="font-size:24px;font-weight:700;color:var(--text);margin:0 0 8px;letter-spacing:-.02em">Crediti &amp; Accesso</h3>
        <p style="font-size:13px;color:var(--text-soft);line-height:1.5;margin:0">Come funzionano i crediti, i livelli di accesso e le opzioni di download.</p>
      </div>
      <div style="background:var(--card);border:2px solid var(--line);border-radius:16px;overflow:hidden">
        <div class="faq-item" aria-expanded="false" style="display:flex;align-items:center;justify-content:space-between;padding:22px 28px;cursor:pointer;transition:background .2s;border-bottom:1px solid var(--line)" onmouseover="this.style.background='var(--bg)'" onmouseout="this.style.background=''"><div class="faq-inner" onclick="toggleFAQ(this.parentElement)" style="cursor:pointer;flex:1"><div style="font-size:15px;font-weight:700;color:var(--text);margin-bottom:4px" data-i18n="help_why_blocked">Perché alcuni report sono bloccati?</div><div style="font-size:12px;color:var(--text-soft);line-height:1.5"><span data-i18n="help_blocked_preview">Livelli di accesso e requisiti di crediti.</span></div><div class="faq-a-wrap"><div class="faq-a" style="font-size:14px;color:var(--text-soft);line-height:1.7;padding-top:14px">Alcuni report richiedono un numero minimo di sessioni per essere affidabili. Ad esempio, il report "Errori Ricorrenti" ha bisogno di almeno 3 sessioni per distinguere un errore occasionale da un pattern.</div></div></div><span class="material-symbols-outlined" style="color:var(--text-soft);opacity:.4;flex-shrink:0;transition:all .3s;margin-left:16px">chevron_right</span></div>
        <div class="faq-item" aria-expanded="false" style="display:flex;align-items:center;justify-content:space-between;padding:22px 28px;cursor:pointer;transition:background .2s;border-bottom:1px solid var(--line)" onmouseover="this.style.background='var(--bg)'" onmouseout="this.style.background=''"><div class="faq-inner" onclick="toggleFAQ(this.parentElement)" style="cursor:pointer;flex:1"><div style="font-size:15px;font-weight:700;color:var(--text);margin-bottom:4px" data-i18n="help_credits_fail">I crediti si consumano se il report fallisce?</div><div style="font-size:12px;color:var(--text-soft);line-height:1.5"><span data-i18n="help_credits_fail_preview">Policy su fallimenti e rimborsi.</span></div><div class="faq-a-wrap"><div class="faq-a" style="font-size:14px;color:var(--text-soft);line-height:1.7;padding-top:14px">No. I crediti vengono scalati solo quando il report viene completato con successo. Se un report va in errore, puoi riprovarlo senza costi aggiuntivi.</div></div></div><span class="material-symbols-outlined" style="color:var(--text-soft);opacity:.4;flex-shrink:0;transition:all .3s;margin-left:16px">chevron_right</span></div>
        <div class="faq-item" aria-expanded="false" style="display:flex;align-items:center;justify-content:space-between;padding:22px 28px;cursor:pointer;transition:background .2s;border-bottom:1px solid var(--line)" onmouseover="this.style.background='var(--bg)'" onmouseout="this.style.background=''"><div class="faq-inner" onclick="toggleFAQ(this.parentElement)" style="cursor:pointer;flex:1"><div style="font-size:15px;font-weight:700;color:var(--text);margin-bottom:4px" data-i18n="help_download">Posso scaricare i report?</div><div style="font-size:12px;color:var(--text-soft);line-height:1.5"><span data-i18n="help_download_preview">Opzioni di export disponibili.</span></div><div class="faq-a-wrap"><div class="faq-a" style="font-size:14px;color:var(--text-soft);line-height:1.7;padding-top:14px">Sì. Ogni report può essere scaricato come file di testo. I report includono il punteggio, la data, e il testo completo dell'analisi.</div></div></div><span class="material-symbols-outlined" style="color:var(--text-soft);opacity:.4;flex-shrink:0;transition:all .3s;margin-left:16px">chevron_right</span></div>
        <div class="faq-item" aria-expanded="false" style="display:flex;align-items:center;justify-content:space-between;padding:22px 28px;cursor:pointer;transition:background .2s" onmouseover="this.style.background='var(--bg)'" onmouseout="this.style.background=''"><div class="faq-inner" onclick="toggleFAQ(this.parentElement)" style="cursor:pointer;flex:1"><div style="font-size:15px;font-weight:700;color:var(--text);margin-bottom:4px" data-i18n="help_profile_influence">Il mio profilo influenza i report?</div><div style="font-size:12px;color:var(--text-soft);line-height:1.5"><span data-i18n="help_profile_preview">Come la tua storia e le impostazioni guidano l'AI.</span></div><div class="faq-a-wrap"><div class="faq-a" style="font-size:14px;color:var(--text-soft);line-height:1.7;padding-top:14px">Sì. Obiettivi, settore, preferenze di feedback e lingua madre aiutano l'AI a produrre consigli più pertinenti. Più il profilo è completo, più i report rispecchiano il tuo contesto reale.</div></div></div><span class="material-symbols-outlined" style="color:var(--text-soft);opacity:.4;flex-shrink:0;transition:all .3s;margin-left:16px">chevron_right</span></div>
      </div>
    </div>
  </section>

  <!-- Contact CTA -->
  <div style="text-align:center;padding-top:24px;border-top:1px solid var(--line)">
    <p style="font-size:14px;color:var(--text-soft);margin:0 0 16px" data-i18n="help_not_found">Non hai trovato la risposta che cercavi?</p>
    <button onclick="window.location.href='mailto:support@sottotitoli.pro'" style="display:inline-flex;align-items:center;gap:8px;padding:12px 32px;border:none;border-radius:100px;background:var(--cyan);color:#fff;font-size:14px;font-weight:700;font-family:'Manrope',sans-serif;cursor:pointer;box-shadow:0 2px 12px rgba(6,182,212,.25);transition:all .2s" onmouseover="this.style.transform='translateY(-1px)';this.style.boxShadow='0 4px 16px rgba(6,182,212,.35)'" onmouseout="this.style.transform='';this.style.boxShadow='0 2px 12px rgba(6,182,212,.25)'">
      <span class="material-symbols-outlined" style="font-size:18px">contact_support</span>
      Contatta il Supporto
    </button>
  </div>
</div>
`;
}

export async function init() {}
export function destroy() { container = null; }
