#!/usr/bin/env python3
"""Build js/en-ngsl.js from the NGSL 1.2 Learning Dictionary page.

Source: https://www.linguaeruditio.com/Glossary/NGSL/NGSL_gloss.html
(the NGSL — New General Service List — 2,800+ most frequent English words,
with curated POS and learner definitions).

Output: window.EN_NGSL = { "adapt": [rank, "v", "to change ..."], ... }
POS codes are normalized: verb→v noun→n adj→adj adv→adv, everything else 'other'.
Multi-POS entries ("verb, noun") take the first POS.

Requires network (downloads the 3.4 MB glossary HTML on first run).
Usage: python3 scripts/build-en-ngsl.py
"""
import json
import os
import re
import sys
import html as htmlmod
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "js", "en-ngsl.js")
URL = "https://www.linguaeruditio.com/Glossary/NGSL/NGSL_gloss.html"
CACHE = os.path.join(HERE, "data", "ngsl_gloss.html")

POS_NORM = {
    "verb": "v", "noun": "n", "adj": "adj", "adv": "adv",
    "det": "other", "prep": "other", "conj": "other", "pron": "other",
    "aux": "other", "intj": "other", "num": "other",
}

def norm_pos(pos_raw):
    first = pos_raw.split(",")[0].split("/")[0].strip().lower()
    return POS_NORM.get(first, "other")

def main():
    if not os.path.exists(CACHE):
        os.makedirs(os.path.dirname(CACHE), exist_ok=True)
        print(f"Downloading {URL} ...")
        urllib.request.urlretrieve(URL, CACHE)
    raw = open(CACHE, encoding="utf-8", errors="replace").read()

    rows = re.findall(
        r'<tr><td>(\d+)</td>\s*<td><a[^>]*>([^<]+)</a></td>\s*<td><a[^>]*>[^<]*</a></td>\s*<td>([^<]*)</td>\s*<td>(.*?)</td>\s*</tr>',
        raw, re.S)

    entries = {}
    skipped = 0
    for rank, word, pos_raw, rest in rows:
        defn = re.sub(r'<a[^>]*>.*?</a>', ' ', rest)
        defn = re.sub(r'<img[^>]*>', ' ', defn)
        defn = htmlmod.unescape(re.sub(r'\s+', ' ', defn)).strip()
        w = word.strip().lower()
        if not w or not defn:
            skipped += 1
            continue
        entries[w] = [int(rank), norm_pos(pos_raw), defn]

    lines = [
        "/* Auto-generated by scripts/build-en-ngsl.py",
        "   Source: NGSL 1.2 Learning Dictionary (2,800+ most frequent English words)",
        "   https://www.linguaeruditio.com/Glossary/NGSL/NGSL_gloss.html",
        "   Format: \"word\": [rank, pos, definition]   pos: v|n|adj|adv|other",
        "   Used for: offline definitions + curated POS (LEMMA_POS_MAP build). */",
        "window.EN_NGSL = " + json.dumps(entries, separators=(',', ':')) + ";",
    ]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    size_kb = os.path.getsize(OUT) / 1024
    print(f"Wrote {OUT} ({size_kb:.1f} KB) — {len(entries)} entries, {skipped} skipped")

if __name__ == "__main__":
    main()
