#!/usr/bin/env python3
"""Build js/it-kelly.js from the KELLY Italian wordlist (.numbers export).

Source: KELLY project (KELLY wordlist, Italian) — user-provided it_m3.numbers.
Output format (compact, pipe-joined):
    window.IT_KELLY = { "essere": "v|A1", ... };
Pos code kept raw; empty level means "unrated" (runtime falls back to
suffix rules). Comma-lemmas ("il, lo, la") are split; phrase lemmas
(with spaces) are skipped (single-word lookups only).

Requires: pip install numbers-parser
Usage:   python3 scripts/build-it-kelly.py
"""
import sys, os, json

from numbers_parser import Document

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.expanduser("~/Desktop/it_m3.numbers")
OUT = os.path.join(ROOT, "js", "it-kelly.js")

def cell_val(c):
    if c is None:
        return ""
    v = getattr(c, "value", None)
    return v if v is not None else ""

def norm_lemma(s):
    # strip nbsp + whitespace, lowercase
    return s.replace("\xa0", " ").strip().lower()

def main():
    if not os.path.exists(SRC):
        print(f"ERROR: source not found: {SRC}", file=sys.stderr)
        sys.exit(1)

    doc = Document(SRC)
    rows = doc.sheets[0].tables[0].rows()[1:]

    entries = {}   # word -> "pos|level"
    stats = {"split": 0, "phrases_skipped": 0, "unleveled": 0, "malformed": 0}

    for row in rows:
        if len(row) < 3:
            stats["malformed"] += 1
            continue
        lemma_raw = norm_lemma(cell_val(row[0]))
        pos = cell_val(row[1]).strip()
        level = cell_val(row[2]).strip()
        if not lemma_raw or not pos:
            stats["malformed"] += 1
            continue
        # split comma lemmas: "il, lo, la" → il / lo / la
        parts = [p.strip() for p in lemma_raw.replace("(", ",").split(",")]
        # phrase lemmas (multi-word) can't match single-word lookups
        if " " in lemma_raw and "," not in lemma_raw:
            stats["phrases_skipped"] += 1
            continue
        if not level:
            stats["unleveled"] += 1
        for w in parts:
            if not w or " " in w:
                continue
            # keep existing (leveled) entries on collision; else take any
            if w not in entries:
                entries[w] = f"{pos}|{level}"
            elif level and entries[w].endswith("|"):
                entries[w] = f"{pos}|{level}"

    # deterministic output order
    items = sorted(entries.items())
    lines = ['/* Auto-generated by scripts/build-it-kelly.py',
             '   Source: KELLY wordlist (Italian) — user-provided it_m3.numbers',
             '   Format: "word": "pos|CEFR"  (empty CEFR = unrated → suffix fallback)',
             '   POS codes: v n adj adv prep conj det pron num np int abb for */',
             'window.IT_KELLY = {']
    for w, pv in items:
        lines.append(f'  "{w}": "{pv}",')
    lines.append("};")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    size_kb = os.path.getsize(OUT) / 1024
    print(f"Wrote {OUT}")
    print(f"  entries: {len(entries)}")
    print(f"  stats: {stats}")
    print(f"  size: {size_kb:.1f} KB")

if __name__ == "__main__":
    main()
