#!/usr/bin/env python3
"""Build js/lemma-pos-map.js — English word → POS map.

Replaces the dead generator from the sottotitoli-learning repo (that repo
no longer exists; its output had every value set to "other").

Source chain per word (best to worst):
  1. Curated function-word list            → 'other' (articles, preps, conj,
                                             pronouns, auxiliaries, modals,
                                             contraction artifacts)
  2. WordNet synset vote (with morphy for  → n / v / adj / adv
     inflected forms)
  3. Penn tagger (averaged_perceptron)     → n / v / adj / adv / other
  4. 'other'

Key set: union of the existing LEMMA_POS_MAP + CEFR_LEVELS keys.

Requires: pip install nltk; nltk.download('wordnet','averaged_perceptron_tagger','punkt')
Usage:   python3 scripts/build-lemma-pos-map.py
"""
import json
import os
import re

import nltk
from nltk.corpus import wordnet as wn
from nltk import pos_tag, word_tokenize

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "js", "lemma-pos-map.js")
NGSL_SRC = os.path.join(ROOT, "js", "en-ngsl.js")

# ── NGSL curated POS (authoritative override — highest-frequency words) ──
def load_ngsl():
    """word → 'v'|'n'|'adj'|'adv'|'other' from js/en-ngsl.js (if present)."""
    if not os.path.exists(NGSL_SRC):
        return {}
    src = open(NGSL_SRC, encoding="utf-8").read()
    m = re.search(r"window\.EN_NGSL\s*=\s*(\{.*\});", src, re.S)
    if not m:
        return {}
    data = json.loads(m.group(1))
    # values are [rank, pos, definition]
    return {w: (v[1] if isinstance(v, list) and len(v) > 1 else "other") for w, v in data.items()}

# ── Curated function words → 'other' (correct on their own; app shows '—') ──
FUNCTION_WORDS = set("""
a an the some any every each all both few many much such this that these those
my your his her its our their i me we us you he she it they him them
be am is are was were been being isn aren wasn weren ain isn't aren't wasn't weren't
have has had having haven hasn hadn't do does did doing don doesn didn't
can could will would shall should may might must ought
and or but not no nor yet so for of to in on at by with without from into over under
about between through during before after above below up down out off
if than then as because while although though unless until since when where why how
who whom whose which what there here
very just only also even still again
m s t re ve ll d isn aren hasn hadn couldn shouldn wouldn
""".split())

# ── Penn tag → map code ──
def penn_to_code(tag):
    if tag.startswith("NN"): return "n"
    if tag.startswith("VB") or tag == "MD": return "v"
    if tag.startswith("JJ"): return "adj"
    if tag.startswith("RB"): return "adv"
    return "other"

def wordnet_code(word):
    """Most-common POS from WordNet synsets (with morphy for inflections)."""
    votes = {}
    for pos in (wn.VERB, wn.NOUN, wn.ADJ, wn.ADV):
        base = wn.morphy(word, pos) or word
        for s in wn.synsets(base, pos):
            votes[s.pos()] = votes.get(s.pos(), 0) + 1
    if not votes:
        return None
    code_map = {"v": "v", "n": "n", "a": "adj", "s": "adj", "r": "adv"}
    best = max(votes, key=lambda k: votes[k])
    return code_map.get(best)

def classify(word, ngsl):
    if word in FUNCTION_WORDS or len(word) < 2 or "'" in word:
        return "other"
    # 1. NGSL curated POS wins when present (high-frequency, hand-checked)
    if word in ngsl:
        return ngsl[word]
    c = wordnet_code(word)
    if c:
        return c
    try:
        tag = pos_tag(word_tokenize(word))[0][1]
        return penn_to_code(tag)
    except Exception:
        return "other"

def main():
    ngsl = load_ngsl()
    print(f"NGSL overrides loaded: {len(ngsl)}")
    # ── Key set: union of existing maps ──
    keys = set()
    for fname in ("js/lemma-pos-map.js", "js/cefr-levels.js"):
        path = os.path.join(ROOT, fname)
        if not os.path.exists(path):
            continue
        src = open(path, encoding="utf-8").read()
        keys |= set(re.findall(r'"([a-z][a-z0-9\'\-]*)"\s*:', src))
    words = sorted(keys)
    print(f"words to classify: {len(words)}")

    pos_map = {}
    dist = {}
    for w in words:
        code = classify(w, ngsl)
        pos_map[w] = code
        dist[code] = dist.get(code, 0) + 1

    lines = [
        "/* Auto-generated by scripts/build-lemma-pos-map.py (NLTK WordNet + Penn tagger",
        "   POS precedence: NGSL curated (js/en-ngsl.js) > WordNet vote > Penn tagger.",
        "   Values: n | v | adj | adv | other  ('other' renders as '—' in the UI)",
        "   Rebuild: python3 scripts/build-en-ngsl.py && python3 scripts/build-lemma-pos-map.py */",
        "window.LEMMA_POS_MAP = {",
    ]
    for w in words:
        lines.append(f'  "{w}": "{pos_map[w]}",')
    lines.append("};")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    size_kb = os.path.getsize(OUT) / 1024
    print(f"Wrote {OUT}  ({size_kb:.1f} KB)")
    print(f"distribution: {dist}")

if __name__ == "__main__":
    main()
