-- Migration: grammar_reports table for cumulative grammar analysis
-- Each row stores a generated grammar report for a session

CREATE TABLE IF NOT EXISTS grammar_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  session_id UUID REFERENCES sessions(id) ON DELETE SET NULL,
  
  -- Report metadata
  status TEXT NOT NULL DEFAULT 'processing', -- processing, complete, error
  content_language TEXT NOT NULL DEFAULT 'en',
  explanation_language TEXT NOT NULL DEFAULT 'en',
  model_used TEXT,
  
  -- Aggregated results
  total_lines INTEGER DEFAULT 0,
  lines_with_errors INTEGER DEFAULT 0,
  error_count INTEGER DEFAULT 0,
  
  -- Categories (JSON for flexibility)
  error_categories JSONB DEFAULT '{}',
  -- Example: {"verb_tense":5, "subject_verb":3, "preposition":2, "article":4}
  
  -- Top errors with examples
  top_errors JSONB DEFAULT '[]',
  -- Example: [{"error":"he go → he goes", "count":3, "category":"subject_verb"}]
  
  -- Personalized advice (generated by LLM, cross-refs profile + history)
  personalized_advice TEXT,
  
  -- Full corrected transcript (optional, for display)
  corrected_transcript TEXT,
  
  -- Reference to previous reports (for cumulative comparison)
  previous_report_id UUID REFERENCES grammar_reports(id),
  improvement_from_previous JSONB, -- {"new_errors":[], "fixed_errors":[], "persistent_errors":[]}
  
  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_grammar_reports_user ON grammar_reports(user_id);
CREATE INDEX IF NOT EXISTS idx_grammar_reports_session ON grammar_reports(session_id);
CREATE INDEX IF NOT EXISTS idx_grammar_reports_status ON grammar_reports(status);
CREATE INDEX IF NOT EXISTS idx_grammar_reports_created ON grammar_reports(created_at DESC);

-- RLS: users can only read/write their own reports
ALTER TABLE grammar_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can read own grammar reports"
  ON grammar_reports FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own grammar reports"
  ON grammar_reports FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own grammar reports"
  ON grammar_reports FOR UPDATE
  USING (auth.uid() = user_id);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_grammar_reports_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_grammar_reports_updated_at
  BEFORE UPDATE ON grammar_reports
  FOR EACH ROW EXECUTE FUNCTION update_grammar_reports_updated_at();
