-- ============================================================================
-- Learner — AI-generated mission lessons (Phase 2)
-- Each row = one personalized, objectives-driven lesson generated by
-- gpt-4o-mini (supabase/functions/generate-learner-content) and seeded with
-- the user's REAL words (word banks + spaced review).
-- content JSONB shape:
--   { title, subtitle, objective,
--     words: [{it,en,pos,cefr,example_it,example_en}],
--     convo: [{role,text,translation}] }
-- Idempotent — safe to re-run in the Supabase SQL editor.
-- ============================================================================

CREATE TABLE IF NOT EXISTS learner_lessons (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  lesson_type TEXT NOT NULL DEFAULT 'mission',
  focus TEXT,                        -- e.g. 'work', 'travel', profile.domain
  title TEXT NOT NULL,               -- Italian mission title
  subtitle TEXT,
  objective TEXT,                    -- SMART objective (Italian)
  content JSONB NOT NULL DEFAULT '{}'::jsonb,
  source_profile JSONB,              -- { level, seed_count } for the generation
  status TEXT DEFAULT 'completed',
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_learner_lessons_user
  ON learner_lessons(user_id, created_at DESC);

-- ── RLS (safe to re-run) ──
ALTER TABLE learner_lessons ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "learner_lessons_select_own" ON learner_lessons;
CREATE POLICY learner_lessons_select_own
  ON learner_lessons FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "learner_lessons_insert_own" ON learner_lessons;
CREATE POLICY learner_lessons_insert_own
  ON learner_lessons FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "learner_lessons_update_own" ON learner_lessons;
CREATE POLICY learner_lessons_update_own
  ON learner_lessons FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "learner_lessons_delete_own" ON learner_lessons;
CREATE POLICY learner_lessons_delete_own
  ON learner_lessons FOR DELETE
  USING (auth.uid() = user_id);
